### PR TITLE
Properly munge inbound data in all cases. Fixes #187.

### LINKED ISSUE #187: Fix dynamic vars on refresh
The inbound data to storage is not being properly munged in the `switch` statement for case `'firstParty'` and case `'isVisible'`. This leads to incorrect or no data for how many sites the user has visited in the UI.

See [this comment](https://github.com/mozilla/lightbeam-we/pull/180#issuecomment-325823113) for details.

### PR DESCRIPTION
**Pull request by biancadanforth**
Dynamic vars were not updating correctly with the first party count in the switch statement for the `isVisible` and `firstParty` cases in `store.setWebsite`.

### CODE REVIEW

**Comment by biancadanforth** [comment]
@jonathanKingston , there might be a more elegant way to do this, but this works. :)

File: js/store.js [hunk 1]
```diff
@@ -251,19 +251,23 @@ const store = {
           break;
         case 'isVisible':
           if ('isVisible' in website
-              && website.isVisible === true) {
-            break;
+              && website.isVisible === true
+              && value === 0) {
```
Comment (jonathanKingston) [inline js/store.js]: I'm lost, isn't this doing exactly the same other than allowing perhaps different values later?

File: js/store.js [hunk 2]
```diff
@@ -251,19 +251,23 @@ const store = {
...
-            break;
+              && website.firstParty === true
+              && value === 0) {
+            // once a website is a first party, it will always be drawn as one
+            value = 1;
           }
-          website.firstParty = value;
+          website[key] = value;
           if (value) {
-            website.isVisible = true;
```
Comment (jonathanKingston) [inline js/store.js]: This line here is the only cahnge I can see^

**Comment by biancadanforth** [comment]
@jonathanKingston , made changes as we discussed in slack. It's much cleaner now. Let me know what you think!
